# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tas Game Makers
email: hello@tasgamemakers.com
description: >- # this means to ignore newlines until "baseurl:"
  Supporting Tasmanian creatives. We're inclusive, creative, passionate about making games, and proudly Tasmanian.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tasgamemakers.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-149359508-1
discord_url: https://discord.gg/EYP7FVAWrf
facebook_url: https://www.facebook.com/groups/tasgm/
twitter: tasgamemakers
header_pages:
  - _pages/events.md
  - _pages/membership.md
  - _pages/code-of-conduct.md
  - _pages/about-us.md

# the API endpoint that users can POST an email to and receive via mail a link
# to manage their billing info (if that email is for a valid member)
manage_membership_endpoint: https://tasgamemakers.azurewebsites.net/api/get_portal_link 

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.
      layout: "page"
      show_in_header: true
      main_class: main__dark # An additional class to attach to the <main> tag for secondary pages.
  - scope:
      path: ""
      type: "events"
    values:
      permalink: /events/:year/:month/:day/:title/
      layout: "event"
      main_class: main__dark
      
# Create a collection called 'events', whose content can be found in /_events.
collections:
  events:
    output: true # Make these items generate documents

# Build all posts, including ones with a date in the future.
future: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
